/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _codehandler_h_
#define _codehandler_h_
//---------------------------------------------------------------------------------
extern const unsigned char codehandler[];
extern const int codehandler_size;
//---------------------------------------------------------------------------------
#endif //_codehandler_h_
//---------------------------------------------------------------------------------
